const axios = require("axios");

module.exports = {
  config: {
    name: "fbtoken",
    version: "1.0.0",
    author: "vernex",
    description: "Get a fresh Facebook token generated by the API",
    cooldowns: 5,
    dependencies: {
      axios: ""
    }
  },

  run: async function ({ api, event }) {
    const { threadID, messageID } = event;

    try {
      await api.sendMessage("⏳ Fetching Facebook token from server...", threadID, messageID);

      const response = await axios.get("https://haji-mix.up.railway.app/api/fbtoken");
      const data = response.data;

      if (!data.status || !data.result || !data.result.token) {
        return api.sendMessage("❌ Failed to retrieve a Facebook token from the server.", threadID, messageID);
      }

      const token = data.result.token;

      const reply = `
════『 𝗙𝗕 𝗧𝗢𝗞𝗘𝗡 』════

🔐 Access Token:
${token}

📢 Use this token responsibly. Do not share it publicly.

> Thank you for using our bot system.
      `.trim();

      return api.sendMessage(reply, threadID, messageID);
    } catch (err) {
      console.error("❌ Error in /fbtoken:", err.message);
      return api.sendMessage(`❌ Error: ${err.message}`, threadID, messageID);
    }
  }
};
